### ISSUE TITLE
[Request] Clearly document vanilla configuration values

### ISSUE THREAD

**Issue by ajsglist** [qwbarch/lc-mirage#19]
Howdy, I've been setting up and tinkering with Mirage for a little while now, and just wanted to pass along a suggestion to make it easier for other people to get set up.

It would be nice if you included explicit documentation of what the vanilla behavior is inside the config to prevent potential confusion -- and help retain vanilla functionality where desired.  You mention vanilla settings for one of the config options, but I think it would be ideal to simply note "Vanilla = true" or "Vanilla = false" for options that are modifications of the vanilla settings.

e.g. "Whether the credits penalty should be applied during the end of a round.
Setting type: Boolean
Default value: false
EnablePenalty = false
"

could be

"Whether the credits penalty should be applied during the end of a round.
Setting type: Boolean
Default value: false
Vanilla: true
EnablePenalty = false
"

Thanks for the consideration

edit: removed "#" character from config quotes to avoid github reformatting

**Comment by qwbarch** [comment]
Thanks for the feedback, I plan on redoing the entire configuration eventually to make it easier to understand.  
The main reason I've left everything as-is for now is to ensure backwards compatibility.  
Anyone who has a previous version of the mod shouldn't have to redo the same setting because I decided to rename the config key, for example.

For now I'll probably explain it a bit better on the README, but other than that, the config will have to stay as-is until I release a major update (which is the only time I'm willing to completely change the config).

**Comment by qwbarch** [comment]
Made the README explain how to disable the extra features: https://github.com/qwbarch/lc-mirage#what-configuration-options-should-i-use-for-a-more-vanilla-experience
