### ISSUE TITLE
Add configuration options for recording deletion

### ISSUE THREAD

**Issue by qwbarch** [qwbarch/lc-mirage#22]
Add options for the following:
- Delete recordings on round start
- Delete recordings on game start/end
- Don't delete any recordings (user will need to manually handle their recordings)

**Comment by ajsglist** [comment]
Adding on to this after looking at [1.0.9]'s options, I think there's high value in letting players opt in to storing voice files for longer (e.g. "keep last 1000" voice files), persistently through game sessions.  This would allow masked enemies encountered earlier in play sessions to say things players wouldn't have heard quite so recently.

At least based on how 1.0.9 is set up, this would require a way to disable "delete on game close" and separating "DeleteRecordingsPerRound" into two separate settings (since "false" will currently clear the voice files after the run is over)

Thanks for the consideration

**Comment by qwbarch** [comment]
The main reason I didn't add a ``delete on game close`` yet is because I didn't know if it'd make sense to have an option like that networked, since some players might expect the recordings to auto-delete.

Next update I'll just add a local-only config option and make a note about it not being synced inside the config

**Comment by qwbarch** [comment]
@ajsglist Added a config option to not delete anything at all in the latest version
