### ISSUE TITLE
Make the level badge can be removed (player and masker)

### ISSUE THREAD

**Issue by CoolLKKPS** [qwbarch/lc-mirage#25]
same as topic, so this feedback are also send in here: https://github.com/HomelessGinger/MaskedEnemyOverhaul/issues/17

**Comment by qwbarch** [comment]
What's the level badge? Sorry not sure what it is

**Comment by qwbarch** [comment]
> @qwbarch https://thunderstore.io/c/lethal-company/p/ironbean/Remove_Level_Badge this mod can remove player level badge, but doesn't affect masker

Thanks, I'll take a look at this sometime this week

> btw can i ask uh... is EnableMask and EnableArmsOut config options are compatible with MaskedEnemyOverhaul? bc that mod also have same function

It shouldn't conflict, but you can always set them to false for one of the mods if it does.  
**Note:** MaskedEnemyOverhaul currently conflicts with Mirage, where it causes the mimicking voice to not match the player's suit.  
You can see more about the issue here: https://github.com/HomelessGinger/MaskedEnemyOverhaul/issues/18

**Comment by qwbarch** [comment]
Keeping this issue opened so I actually remember to take a look 😂

**Comment by qwbarch** [comment]
I think that'd be out of scope for my mod. Mods that change the player size should (imo) modify the masked enemies as well (of whomever the mimicking player is set to).
I recommend asking the authors of those mods to make it work with masked enemies instead

**Comment by qwbarch** [comment]
> @qwbarch https://thunderstore.io/c/lethal-company/p/ironbean/Remove_Level_Badge this mod can remove player level badge, but doesn't affect masker

Ah I just realized I misunderstood your request from earlier. I thought the player level badge was not being mimicked properly, but your request is to have that mod remove player level badges on masked enemies as well.

Similarly to the other mods, it'd make more sense for them to support it directly. Try asking the author to have their cosmetic changes apply to masked enemies as well.

Sorry I couldn't help you here, but it's definitely out of scope for my mod since it'd be too labour intensive to try and patch things for every cosmetic mod out there

**Comment by qwbarch** [comment]
For anything that has textures, I *might* be able to copy it over to the masked enemies, but I don't have time to look into it anytime soon.

Might be able to generically support copying cosmetics with textures but we'll have to see

**Comment by qwbarch** [comment]
FYI when requesting a mod to have their cosmetics support masked enemies, there's no need to mention mirage, since the point is to have it support masked enemies itself.

Regarding ``LCCustomDifficulty`` and ``LethalMidgets``, I tried looking them up on discord and couldn't find a mod release page so I'm afraid I can't contact them myself either.

Sorry I wasn't able to help much!

**Comment by CoolLKKPS** [comment]
sad okay, i don't think they will continue maintain LethalMidgets, so i guess i have to wait some people to fork, hope that won't take long...
