### ISSUE TITLE
Legal issue

### ISSUE THREAD

**Issue by exverge-0** [qwbarch/lc-mirage#40]
This repository contains Assembly-CSharp (entirety of Lethal Company game code), Dissonance VoIP, and most if not all of the Unity engine modules used to make Lethal Company under the lib folder. Providing them freely on this repository is a form of piracy and should be removed from the repository.

**I am not a lawyer, nor am I affiliated with Lethal Company, Dissonance, or Unity.** I am simply stating this so that these files are removed from the repository.

**Comment by qwbarch** [comment]
Thanks, wasn't aware of this being a legal issue, which I'll fix soon.

Note to self (thanks to ``Lordfirespeed``):
```
<PackageReference Include="LethalCompany.GameLibs.Steam" Version="49.0.0-alpha.1" />
```

**Comment by exverge-0** [comment]
You should see GitHub’s docs on removing sensitive data to purge the files in order to prevent any further potential issues. Do note that if you do this it will rewrite the commit history which may cause some problems on local repositories

**Comment by qwbarch** [comment]
Yeah I was going to do that yesterday, but it was late so I left it for when I woke up.  
Decided it'd be easier to simply wipe the git history instead, but that should work either way since the game assemblies are no longer present (except on the fork).  
I deleted the releases as well just in case since those contain them as well.

Thanks again for the heads up, really appreciate it!
